### ISSUE TITLE
新手入门，运行代码提示用户警告，求助~

### ISSUE THREAD

**Issue by Licko0909** [yuweiming70/Style_Migration_For_Artistic_Font_With_CNN#3]
![image](https://user-images.githubusercontent.com/27897166/42672588-70aaf472-8699-11e8-8b6c-c5e839f290c8.png)

我下载了大神您的代码案例等等，然后设置了下载好的代码案例等等这个文件夹作为工作路径，看了下好像没有别的需要设置，我就直接去跑代码，提示出现警告，有点不太懂，望指点~

**Comment by koishi70** [comment]
我想可能是你的输出目录没写对，我刚更新了一些使用的例子，在首页那，在cmd里输入示例代码就可以了，你对照着看看是不是没填对？

**Comment by Licko0909** [comment]
万分感谢，原来是在cmd里面输入，没试过，不太会用




发自网易邮箱大师


在2018年7月13日 13:05，yuweiming70<notifications@github.com> 写道：

我想可能是你的输出目录没写对，我刚更新了一些使用的例子，在首页那，在cmd里输入示例代码就可以了，你对照着看看是不是没填对？
